### ISSUE TITLE
Deployment of the theme

### ISSUE THREAD

**Issue by chrisvidal** [scottbedard/scottbedard.net#1]
Hi Scott,
getting inspired by your project and I am wondering how do you deploy the theme?
after the build, vuecli must be creating a `dist` folder, hence my question how do you deploy the vue app?
thanks

**Comment by scottbedard** [comment]
All of my websites are deployed using [Laravel Envoyer](https://envoyer.io/). The basic workflow is as follows

1. Wire up push-to-deploy hook to kick things off
2. Clone repository and build theme via `yarn build`
3. Run `php artisan october:up`
4. Make new build live and delete the old one (this is handled for me by Envoyer)

Hope this helps!

**Comment by chrisvidal** [comment]
thanks for this.

my question is more in regards to the VueJs build in the folder `dist` that will not been visible by OctoberCMS. how does this actually work?
